# Change these first
owner: FernandoQuiguantar # Tu usuario de GitHub
repo: TallerGHA2 # El nombre de tu repositorio

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Sitio Caido Prueba
    url: https://sitio-que-no-existe-12345.com # Sitio roto para probar alertas

status-website:

 
  baseUrl: /TallerGHA2
  
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor de Servicios
  introTitle: "**Upptime** Monitoreo de Servicios"
  introMessage: Página de estado en tiempo real impulsada por GitHub Actions[cite: 1].
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
