# Change these first
owner: FernandoQuiguantar
repo: TallerGHA2

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Sitio Caido Prueba
    url: https://sitio-que-no-existe-12345.com

status-website:
  baseUrl: /TallerGHA2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor de Servicios
  introTitle: "**Upptime** Monitoreo de Servicios"
  introMessage: Pagina de estado en tiempo real impulsada por GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
